### ISSUE TITLE
Cannot open file from command line

### ISSUE THREAD

**Issue by Psy-Fer** [dietvin/pod5Viewer#1]
Hello,

Nice tool. It works really smoothly. Way faster than HDFView. Nice work!

When I try to open a file from the command line, like instructed in the README.md I get the following error

pod5Viewer multi_fast5_zip_v0.pod5

```
Traceback (most recent call last):
  File "/home/jamfer/pvenv/pod5viewer/bin/pod5Viewer", line 8, in <module>
    sys.exit(main())
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5Viewer/__main__.py", line 38, in main
    window = Pod5Viewer(file_paths)
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5Viewer/pod5Viewer.py", line 85, in __init__
    self.load_files(file_paths)
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5Viewer/pod5Viewer.py", line 391, in load_files
    file_navigator_data = self.data_handler.ids_to_path()
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5Viewer/dataHandler.py", line 57, in ids_to_path
    raise e
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5Viewer/dataHandler.py", line 54, in ids_to_path
    [self.dataset_reader.get_reader(file).read_ids for file in file_paths]))
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5Viewer/dataHandler.py", line 54, in <listcomp>
    [self.dataset_reader.get_reader(file).read_ids for file in file_paths]))
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5/dataset.py", line 228, in get_reader
    return self._get_reader(Path(path))
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5/dataset.py", line 211, in _get_reader
    return Reader(path)
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5/reader.py", line 666, in __init__
    ) = self._open_arrow_table_handles(self._path)
  File "/home/jamfer/pvenv/pod5viewer/lib/python3.10/site-packages/pod5/reader.py", line 700, in _open_arrow_table_handles
    raise FileNotFoundError(f"Failed to open pod5 file at: {path}")
FileNotFoundError: Failed to open pod5 file at: /tmp/multi_fast5_zip_v0.pod5

```

If I instead run 
```pod5Viewer```
with no arguments, then the window opens, and I can load a file using the menu, and it all works as expected.

I am running on Linux (Pop!_OS)
I got the error installing from pip as well as installing from source (`pip install .`)

James

**Comment by dietvin** [comment]
Hi James,

thanks for the feedback and pointing out the issue. I could replicate it on my Ubuntu system as well. 

I just pushed a fix so you should be able to open files directly from the command line now after installing it again from source. 

Let me know if the problem persists on your system.

Best
Vincent

**Comment by Psy-Fer** [comment]
Hey Vincent,

Yep that fixed it. Thanks!

Again, great work :)
James
